language: node_js
node_js: node
services: mongodb
env:
  matrix:
    secure: JdxFhXRF7u2gU23FIbZd6F+e6Zavnml/ZzHQkapcas+phcdf8a4PPFLNTihvl0otNq9VLlUMxj/eQjq1pCq9igFbNBHpZergxowmEPygqWhiDRnrSp4bKzkVtAG6XOF0r3D6mGLMGYB3gv/LWz7qi4K/T0DPng8pbeYgd0MYDHd5SF3/VFt5IeQoUkOhCT0q7xtDSFllfUf0b+0RkuFiad2Lf+/2NAsRmk2SDgeSlLbnriquAcP2OBa/U0kkhMIpsdSfMf9K6OE1eNFmwA2vQtntV0q3HIRl55eo5jojRJb3on9YThWA59VMFPVvVPvzjsmIL3KiJGSp77lZXzvuZuORkLuS/fev8A4DSzZrSu55nHFCoWMlctw40b/wi1RHKtMy9UWmb5Z704cWNDlaLeKvfc39leMhrMnpjMZC9FbyZYA5ECfYZEECs0BVTjZ1VIC9lA8g+NnyXckXKCJKkbuKdhIQqZUf52bzUA+az2zR/lwm6/Izn9s19wJJAPBpJ5RSLFouqgwmqa8sJPfr6xf7PDWf6klfPY9eQXIPuI+KCQ0tzeFiROznvF3oPp1gliNUwpQIyUJEtJ+BQ8X5yh8ihZHs50NmZtBdVT8wsTe+XvRgxSHOh9JdX/ILemA2c4DLhkOFtcIvGjJ0xYsIcnWQjnTp6KVHBkbMkWPS9zo=
